#Se esta usando h2 para db en memory
#Tablas
    create table Cliente (
        id bigint generated by default as identity,
        direccion varchar(255),
        edad integer,
        genero varchar(255),
        idPersona bigint,
        identificacion varchar(255) not null,
        nombre varchar(255) not null,
        telefono varchar(255),
        contrasenia varchar(16) not null,
        estado boolean not null,
        primary key (id)
    );
    create table Cuenta (
        id bigint generated by default as identity,
        estado boolean not null,
        nroCuenta varchar(6) not null,
        saldoInicial double not null,
        tipoCuenta varchar(255) not null,
        IdCliente bigint,
        primary key (id)
    );
    create table Movimiento (
        id bigint generated by default as identity,
        fecha timestamp not null,
        saldo double not null,
        tipoMovimiento varchar(255) not null,
        valor double not null,
        IdCuenta bigint,
        primary key (id)
    );

    alter table Cuenta 
       add constraint UK_57hofmmxejhxiufmbec4k7tsp unique (nroCuenta);

    alter table Cuenta 
       add constraint FKrk16k04r8qbhrbpeb88rnqm1w 
       foreign key (IdCliente) references Cliente;

    alter table Movimiento 
       add constraint FK5a3cf0okypjy3q3bww8pxif9n 
       foreign key (IdCuenta) references Cuenta;